changelog:
  categories:
    - title: 🏕 Features
      labels:
        - features
        - user story
    - title: ✨ Enhancements
      labels:
        - enhancement
    - title: 🧹 Chores
      labels:
        - chore
    - title: 🧪 Tests
      labels:
        - test
    - title: 💪 Improvements
      labels:
        - improvement
    - title: 🐛 Bugs
      labels:
        - bug
