services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1}
      POSTGRES_DB: whmapper
      PGDATA: /data/postgres
    volumes:
     - postgres:/data/postgres
    networks:
     - net

  redis:
    image: redis:7-alpine
    restart: always
    networks:
     - net

  whmapper:
    image: ghcr.io/pfh59/eve-whmapper:latest
    restart: unless-stopped
    environment:
     - EveSSO__ClientId=xxxxxxxxx
     - EveSSO__Secret=xxxxxxxxx
     - ConnectionStrings__DatabaseConnection=server=db;port=5432;database=whmapper;User Id=postgres;Password=secret
     - ConnectionStrings__RedisConnection=redis:6379
     - Serilog__MinimumLevel__Default=Warning
     - Serilog__MinimumLevel__Override__Microsoft.EntityFrameworkCore.Database.Command=Warning
     - DisableSignalRCertificateValidation=true
    links:
      - db     
    depends_on:
      - db 
    networks:
     - net
    volumes:
     - ./Logs:/app/Logs

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/:/etc/nginx/certs/:ro
    links:
      - whmapper
    depends_on:
      - whmapper
    networks:
      - net
networks:
  net:

volumes:
    postgres:
