using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WHMapper.Migrations
{
    /// <inheritdoc />
    public partial class Add_WHMapAccess_And_Remove_Legacy : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Drop legacy tables if they exist
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""WHAccessWHMap"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Accesses"" CASCADE;");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Admins"" CASCADE;");

            // Create the new MapAccesses table if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""MapAccesses"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""WHMapId"" integer NOT NULL,
                    ""EveEntityId"" integer NOT NULL,
                    ""EveEntityName"" character varying(255) NOT NULL,
                    ""EveEntity"" integer NOT NULL,
                    ""GrantedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_MapAccesses"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_MapAccesses_Maps_WHMapId"" FOREIGN KEY (""WHMapId"")
                        REFERENCES ""Maps"" (""Id"") ON DELETE CASCADE
                );
            ");

            // Create index if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_MapAccesses_WHMapId_EveEntityId_EveEntity""
                ON ""MapAccesses"" (""WHMapId"", ""EveEntityId"", ""EveEntity"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MapAccesses");

            // Recreate legacy tables
            migrationBuilder.CreateTable(
                name: "Accesses",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    EveEntity = table.Column<int>(type: "integer", nullable: false),
                    EveEntityId = table.Column<int>(type: "integer", nullable: false),
                    EveEntityName = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Accesses", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Admins",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    EveCharacterId = table.Column<int>(type: "integer", nullable: false),
                    EveCharacterName = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Admins", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "WHAccessWHMap",
                columns: table => new
                {
                    WHAccessesId = table.Column<int>(type: "integer", nullable: false),
                    WHMapId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_WHAccessWHMap", x => new { x.WHAccessesId, x.WHMapId });
                    table.ForeignKey(
                        name: "FK_WHAccessWHMap_Accesses_WHAccessesId",
                        column: x => x.WHAccessesId,
                        principalTable: "Accesses",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_WHAccessWHMap_Maps_WHMapId",
                        column: x => x.WHMapId,
                        principalTable: "Maps",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Accesses_EveEntityId_EveEntity",
                table: "Accesses",
                columns: new[] { "EveEntityId", "EveEntity" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Admins_EveCharacterId",
                table: "Admins",
                column: "EveCharacterId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_WHAccessWHMap_WHMapId",
                table: "WHAccessWHMap",
                column: "WHMapId");
        }
    }
}
