// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WHMapper.Data;

#nullable disable

namespace WHMapper.Migrations
{
    [DbContext(typeof(WHMapperContext))]
    partial class WHMapperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WHMapper.Models.Db.WHInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorCharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorCharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OwnerEveEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerEveEntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerEveEntityId", "OwnerType")
                        .IsUnique();

                    b.ToTable("Instances", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHInstanceAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EveEntity")
                        .HasColumnType("integer");

                    b.Property<int>("EveEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EveEntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WHInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WHInstanceId", "EveEntityId", "EveEntity")
                        .IsUnique();

                    b.ToTable("InstanceAccesses", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHInstanceAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EveCharacterId")
                        .HasColumnType("integer");

                    b.Property<string>("EveCharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<int>("WHInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WHInstanceId", "EveCharacterId")
                        .IsUnique();

                    b.ToTable("InstanceAdmins", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHJumpLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JumpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ShipItemId")
                        .HasColumnType("bigint");

                    b.Property<float?>("ShipMass")
                        .HasColumnType("real");

                    b.Property<int?>("ShipTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("WHSystemLinkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WHSystemLinkId");

                    b.HasIndex("CharacterId", "JumpDate")
                        .IsUnique();

                    b.ToTable("JumpLogs", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("WHInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("WHInstanceId");

                    b.ToTable("Maps", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHMapAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EveEntity")
                        .HasColumnType("integer");

                    b.Property<int>("EveEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EveEntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WHMapId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WHMapId", "EveEntityId", "EveEntity")
                        .IsUnique();

                    b.ToTable("MapAccesses", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("SoloarSystemId")
                        .HasColumnType("integer");

                    b.Property<int>("SystemStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MapId", "SoloarSystemId")
                        .IsUnique();

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WHId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WHId", "Name")
                        .IsUnique();

                    b.ToTable("Signatures", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte>("NameExtension")
                        .HasColumnType("smallint");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision");

                    b.Property<float>("SecurityStatus")
                        .HasColumnType("real");

                    b.Property<int>("SoloarSystemId")
                        .HasColumnType("integer");

                    b.Property<int>("WHMapId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WHMapId", "Name")
                        .IsUnique();

                    b.HasIndex("WHMapId", "SoloarSystemId")
                        .IsUnique();

                    b.ToTable("Systems", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSystemLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndOfLifeStatus")
                        .HasColumnType("integer");

                    b.Property<int>("IdWHSystemFrom")
                        .HasColumnType("integer");

                    b.Property<int>("IdWHSystemTo")
                        .HasColumnType("integer");

                    b.Property<int>("MassStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("WHMapId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdWHSystemFrom");

                    b.HasIndex("IdWHSystemTo");

                    b.HasIndex("WHMapId", "IdWHSystemFrom", "IdWHSystemTo")
                        .IsUnique();

                    b.ToTable("SystemLinks", (string)null);
                });

            modelBuilder.Entity("WHMapper.WHRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EveEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("SolarSystemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MapId", "SolarSystemId", "EveEntityId")
                        .IsUnique();

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHInstanceAccess", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHInstance", null)
                        .WithMany("InstanceAccesses")
                        .HasForeignKey("WHInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHInstanceAdmin", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHInstance", null)
                        .WithMany("Administrators")
                        .HasForeignKey("WHInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHJumpLog", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHSystemLink", null)
                        .WithMany("JumpHistory")
                        .HasForeignKey("WHSystemLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHMap", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHInstance", null)
                        .WithMany("WHMaps")
                        .HasForeignKey("WHInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHMapAccess", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHMap", "WHMap")
                        .WithMany("WHMapAccesses")
                        .HasForeignKey("WHMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WHMap");
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHNote", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHMap", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSignature", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHSystem", null)
                        .WithMany("WHSignatures")
                        .HasForeignKey("WHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSystem", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHMap", null)
                        .WithMany("WHSystems")
                        .HasForeignKey("WHMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSystemLink", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHSystem", null)
                        .WithMany()
                        .HasForeignKey("IdWHSystemFrom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WHMapper.Models.Db.WHSystem", null)
                        .WithMany()
                        .HasForeignKey("IdWHSystemTo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WHMapper.Models.Db.WHMap", null)
                        .WithMany("WHSystemLinks")
                        .HasForeignKey("WHMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.WHRoute", b =>
                {
                    b.HasOne("WHMapper.Models.Db.WHMap", null)
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHInstance", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("InstanceAccesses");

                    b.Navigation("WHMaps");
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHMap", b =>
                {
                    b.Navigation("WHMapAccesses");

                    b.Navigation("WHSystemLinks");

                    b.Navigation("WHSystems");
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSystem", b =>
                {
                    b.Navigation("WHSignatures");
                });

            modelBuilder.Entity("WHMapper.Models.Db.WHSystemLink", b =>
                {
                    b.Navigation("JumpHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
