name: Publish on release

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: publish-release-${{ github.ref }}
  cancel-in-progress: false

env:
  DOTNET_VERSION: '10.0.x'
  REGISTRY: ghcr.io
  REGISTRY_DOCKERHUB: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release_artifacts:
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup .NET 10 🦴
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Extract version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Generate packages (linux x64/arm, Windows x64)
        run: |
            dotnet restore src
            dotnet publish src/WHMapper/WHMapper.csproj -c Release -r linux-x64 --no-self-contained --nologo -o ./release/linux-x64 /p:Version=${{ env.VERSION }}
            dotnet publish src/WHMapper/WHMapper.csproj -c Release -r linux-arm --no-self-contained --nologo -o ./release/linux-arm /p:Version=${{ env.VERSION }}
            dotnet publish src/WHMapper/WHMapper.csproj -c Release -r win-x64 --no-self-contained --nologo -o ./release/win-x64 /p:Version=${{ env.VERSION }}

      - name: Attest packages
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: './release/linux-x64'
  
      - name: Attest packages (linux-arm)
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: './release/linux-arm'
          
      - name: Attest packages (win-x64)
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: './release/win-x64'
      
      - name: Compress and upload to release
        run: |
            zip -r WHMapper.linux-x64.zip ./release/linux-x64 -j
            zip -r WHMapper.linux-arm.zip ./release/linux-arm -j
            zip -r WHMapper.win-x64.zip ./release/win-x64 -j
            gh release upload ${{ github.event.release.tag_name }} WHMapper.linux-x64.zip
            gh release upload ${{ github.event.release.tag_name }} WHMapper.linux-arm.zip
            gh release upload ${{ github.event.release.tag_name }} WHMapper.win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

  prepare_release_docker_image_ghcr:
    needs: [release_artifacts]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          
    steps:
      - name: Prepare platform variables
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV 
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: false
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Authenticate to registry ${{ env.REGISTRY }}
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for ${{ env.REGISTRY }}
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.authors=${{ github.actor }}
            org.opencontainers.image.version=${{ env.VERSION }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest
          flavor: |
            latest=false

      - name: Build and push to ${{ env.REGISTRY }} by digest
        id: build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./src/WHMapper/
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true
          build-args: |
            VERSION=${{ env.VERSION }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
      
      - name: Attest the image
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
            
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: digests-ghcr-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge_release_docker_image_ghcr:
    needs: [prepare_release_docker_image_ghcr]
    permissions:
      packages: write
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: /tmp/digests
          pattern: digests-ghcr-*
          merge-multiple: true
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
        
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest
          flavor: |
            latest=false
      
      - name: Authenticate to registry ${{ env.REGISTRY }}
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:%s ' *)          
            
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
